spring:
  application:
    name: tlais-web-management #项目名称
    #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlais  #tlais是数据库名，前面的内容是固定的
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    username: root #数据库用户名
    password: 123456 #数据库密码
    #mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # MyBatis日志实现，将SQL语句输出到控制台
    map-underscore-to-camel-case: true  # 开启驼峰命名映射，自动将下划线命名转换为驼峰命名
